$(document).ready(()=>{
    $('.sidebar-toggle').click(()=>{
        $('.main-sidebar').toggleClass("active");
        $('.logo_mini').toggleClass("active");
        $('.logo-lg').toggleClass("active");
        $('footer').toggleClass("active");
        $('.logo').toggleClass("active");
    });   
});